# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userregistrationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationcode',
            name='hashcode',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
