# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('base', '0004_userregistrationcode_hashcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='group',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='auth.Group'),
        ),
    ]
